spring:
  main:
    banner-mode: off

logging:
  file:
    name: ${app.settings.log-file}
  level:
    root: info
    parrhesia1000: debug
    parrhesia1000.SessionCallbackHandler: info
#    parrhesia1000.FeedElementCache: info
    org:
      springframework:
        web: debug

app:
  pub: 8531bb63dfbe216e140ed8507b38678f684ae67e0c06512abe5a19e50f0db1c3
  name: parrhesia1000
  debug: false
  settings:
      parent: ${user.home}
      dir: ${app.settings.parent}/.${app.name}
      log-file: ${app.settings.dir}/${app.name}.log
  ui:
    appTitle: "Parrhesia1000"
    initialWidth: 800
    initialHeight: 600
    imageHeight: 200

